name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.4
          - 8.5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.php }}" == "8.5" ]]; then
            composer install --prefer-dist --no-progress --ignore-platform-req=php
          else
            composer install --prefer-dist --no-progress
          fi

      - name: Check types
        run: composer types:check

      - name: Check style
        run: composer style:check

      - name: Run test suite
        run: vendor/bin/pest --coverage --min=100 --coverage-clover=coverage.xml

      -   name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
